export const CHECKING_PENDING = 'CHECKING_PENDING';
export const CHECKING_SUCCESS = 'CHECKING_SUCCESS';
export const CHECKING_ERROR = 'CHECKING_ERROR';
export const CHECKING_COUNT = 'CHECKING_COUNT';

//checkPage 대소문자 수정
