//유저 조회 디스패치 관련
export const EXAMPLE_PAGINATION_PENDING = 'EXAMPLE_PAGINATION_PENDING';
export const EXAMPLE_PAGINATION_SUCCESS = 'EXAMPLE_PAGINATION_SUCCESS';
export const EXAMPLE_PAGINATION_ERROR = 'EXAMPLE_PAGINATION_ERROR';
