export const ORDERS_PENDING = 'ORDERS_PENDING';
export const ORDERS_SUCCESS = 'ORDERS_SUCCESS';
export const ORDERS_ERROR = 'ORDERS_ERROR';
export const STATE_CHANGE = 'STATE_CHANGE';
export const STATE_CHANGE_ERROR = 'STATE_CHANGE_ERROR';
export const SET_FREE_TICKET = 'SET_FREE_TICKET';
export const SET_FREE_TICKET_ERROR = 'SET_FREE_TICKET_ERROR';
