export const ORDERS_PENDING = 'ORDERS_PENDING';
export const ORDERS_SUCCESS = 'ORDERS_SUCCESS';
export const ORDERS_ERROR = 'ORDERS_ERROR';
export const SET_ORDER_STATUS = 'SET_ORDER_STATUS';
export const SET_ORDER_STATUS_ERROR = 'SET_ORDER_STATUS_ERROR';
export const SET_FREE_ORDER = 'SET_FREE_ORDER';
export const SET_FREE_ORDER_ERROR = 'SET_FREE_ORDER_ERROR';
