export const TICKET_PAGINATION_PENDING = 'TICKET_PAGINATION_PENDING';
export const TICKET_PAGINATION_SUCCESS = 'TICKET_PAGINATION_SUCCESS';
export const TICKET_PAGINATION_ERROR = 'TICKET_PAGINATION_ERROR';
export const STATE_CHANGE = 'state_change';
export const STATE_CHANGE_ERROR = 'state_change_error';
